### ISSUE TITLE
repository naming convention

### ISSUE THREAD

**Issue by serein7** [OpenAgInitiative/openag_atlas_rgb#1]
It's not critical, but still would be better to stick to one naming convention with **-** between words instead of **_** as majority of other repos in OpenAgInitiative are using **-**
I.e. rename this one to **openag-atlas-rgb**

**Comment by LeonChambers** [comment]
We decided yesterday to switch to using _ between words and just haven't updated the other repos yet.

**Comment by serein7** [comment]
Got it. Sorry for bothering then.

**Comment by serein7** [comment]
BTW, did you consider to add some tag for sensors? i.e. openag_sensor_atlas_rgb openag_sensor_dht22 and etc as I assume there will be 10-20 of small repos like this and might be messy in the list.
